import type { Category, Coupon, Product, Review } from '../types';

export const defaultCategories: Category[] = [
  { id: '1', name: 'For Her', description: 'Thoughtful gifts she will love', image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=400&h=300&fit=crop', slug: 'for-her', sortOrder: 1, published: true },
  { id: '2', name: 'For Him', description: 'Perfect picks for the special men in your life', image: 'https://images.unsplash.com/photo-1549465220-1a8b923823cd?w=400&h=300&fit=crop', slug: 'for-him', sortOrder: 2, published: true },
  { id: '3', name: 'Birthdays', description: 'Celebrate another year with the perfect present', image: 'https://images.unsplash.com/photo-1607083206869-4c7672f72a7a?w=400&h=300&fit=crop', slug: 'birthdays', sortOrder: 3, published: true },
  { id: '4', name: 'Occasions', description: 'Anniversaries, weddings, and milestone moments', image: 'https://images.unsplash.com/photo-1512909006721-3d0158887362?w=400&h=300&fit=crop', slug: 'occasions', sortOrder: 4, published: true },
  { id: '5', name: 'Under $50', description: 'Great gifts that will not break the bank', image: 'https://images.unsplash.com/photo-1549465220-1a8b923823cd?w=400&h=300&fit=crop', slug: 'under-50', sortOrder: 5, published: true },
  { id: '6', name: 'Partner Picks', description: 'Curated affiliate favourites from trusted stores', image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=400&h=300&fit=crop', slug: 'partner-picks', sortOrder: 6, published: true },
];

export const defaultProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description:
      'Experience studio-quality sound with active noise cancellation, 30-hour battery life, and premium comfort. Perfect for music lovers and professionals.',
    price: 299.99,
    compareAtPrice: 399.99,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=800&fit=crop',
    ],
    category: 'Electronics',
    stock: 50,
    sku: 'WH-PRO-001',
    tags: ['audio', 'wireless', 'premium', 'noise-cancelling'],
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Smart Fitness Watch Pro',
    description:
      'Advanced fitness tracking with heart rate monitoring, GPS, sleep analysis, and 50+ sport modes. Water-resistant up to 50m.',
    price: 249.99,
    compareAtPrice: 349.99,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&h=800&fit=crop',
    ],
    category: 'Electronics',
    stock: 30,
    sku: 'SW-PRO-002',
    tags: ['fitness', 'smartwatch', 'health', 'waterproof'],
    variants: [
      { id: 'v1', name: 'Band Color', options: ['Black', 'Navy', 'Rose Gold', 'Silver'] },
      { id: 'v2', name: 'Size', options: ['Small', 'Medium', 'Large'] },
    ],
    rating: 4.6,
    reviewCount: 189,
    featured: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Premium Cotton T-Shirt',
    description:
      'Ultra-soft 100% organic cotton t-shirt with a perfect fit. Breathable, durable, and ethically made. Available in multiple colors.',
    price: 34.99,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&h=800&fit=crop',
    ],
    category: 'Clothing',
    stock: 100,
    sku: 'TS-ORG-003',
    tags: ['organic', 'cotton', 'casual', 'sustainable'],
    variants: [
      { id: 'v1', name: 'Color', options: ['White', 'Black', 'Navy', 'Gray', 'Olive'] },
      { id: 'v2', name: 'Size', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
    ],
    rating: 4.9,
    reviewCount: 456,
    featured: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Professional Running Shoes',
    description:
      'Engineered for performance with responsive cushioning, breathable mesh, and superior grip. Perfect for runners of all levels.',
    price: 129.99,
    compareAtPrice: 159.99,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&h=800&fit=crop',
    ],
    category: 'Sports & Outdoors',
    stock: 45,
    sku: 'RS-PRO-004',
    tags: ['running', 'sports', 'performance', 'cushioning'],
    variants: [
      { id: 'v1', name: 'Size', options: ['6', '7', '8', '9', '10', '11', '12'] },
      { id: 'v2', name: 'Width', options: ['Regular', 'Wide'] },
    ],
    rating: 4.7,
    reviewCount: 312,
    featured: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Luxury Leather Backpack',
    description:
      'Handcrafted genuine leather backpack with laptop compartment, multiple pockets, and adjustable straps. Perfect for work or travel.',
    price: 189.99,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&h=800&fit=crop',
    ],
    category: 'Home & Living',
    stock: 25,
    sku: 'BP-LUX-005',
    tags: ['leather', 'backpack', 'luxury', 'handcrafted'],
    variants: [{ id: 'v1', name: 'Color', options: ['Brown', 'Black', 'Tan'] }],
    rating: 4.8,
    reviewCount: 87,
    featured: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Bestseller Novel Collection',
    description:
      'Collection of 3 award-winning novels from contemporary authors. Perfect for book lovers and gift giving.',
    price: 49.99,
    images: ['https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop'],
    category: 'Books & Media',
    stock: 60,
    sku: 'BK-COL-006',
    tags: ['books', 'fiction', 'bestseller', 'collection'],
    rating: 4.9,
    reviewCount: 178,
    featured: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Organic Skincare Set',
    description:
      'Complete skincare routine with cleanser, toner, serum, and moisturizer. All-natural, cruelty-free, and suitable for all skin types.',
    price: 89.99,
    compareAtPrice: 119.99,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&h=800&fit=crop',
    ],
    category: 'Beauty & Health',
    stock: 40,
    sku: 'SK-ORG-007',
    tags: ['skincare', 'organic', 'beauty', 'natural'],
    rating: 4.7,
    reviewCount: 203,
    featured: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    description:
      'Extra thick, non-slip yoga mat with alignment marks. Eco-friendly TPE material, includes carrying strap.',
    price: 59.99,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=800&fit=crop'],
    category: 'Sports & Outdoors',
    stock: 55,
    sku: 'YM-PRE-008',
    tags: ['yoga', 'fitness', 'eco-friendly', 'exercise'],
    variants: [{ id: 'v1', name: 'Color', options: ['Purple', 'Blue', 'Pink', 'Green', 'Gray'] }],
    rating: 4.6,
    reviewCount: 145,
    featured: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'aff-1',
    name: 'Luxury Spa Gift Set (Partner Pick)',
    description:
      'A bestselling spa gift basket with bath bombs, candles, and body care essentials—perfect for birthdays and thank-you gifts.',
    price: 49.99,
    compareAtPrice: 64.99,
    images: ['https://images.unsplash.com/photo-1607083206869-4c7672f72a7a?w=800&h=800&fit=crop'],
    category: 'Partner Picks',
    stock: 0,
    sku: 'AFF-SPA-001',
    tags: ['spa', 'self-care', 'affiliate', 'under-50'],
    rating: 4.8,
    reviewCount: 892,
    featured: true,
    purchaseMode: 'affiliate',
    affiliateUrl: 'https://www.amazon.com/s?k=spa+gift+set',
    affiliateVendor: 'Amazon',
    affiliateButtonLabel: 'View on Amazon',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultReviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah@example.com',
    rating: 5,
    title: "Best headphones I've ever owned",
    comment:
      'The sound quality is incredible and the noise cancellation is perfect for my daily commute. Battery life exceeds expectations!',
    verified: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r2',
    productId: '1',
    customerName: 'Mike Chen',
    customerEmail: 'mike@example.com',
    rating: 4,
    title: 'Great value for money',
    comment: 'Really impressed with these headphones. Comfortable for long sessions and the sound is crisp.',
    verified: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r3',
    productId: '3',
    customerName: 'Emma Davis',
    customerEmail: 'emma@example.com',
    rating: 5,
    title: 'Perfect fit and amazing quality',
    comment:
      'Love this t-shirt! The organic cotton is so soft and it fits perfectly. Will definitely buy more colors.',
    verified: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const defaultCoupons: Coupon[] = [
  {
    id: 'c1',
    code: 'WELCOME10',
    description: '10% off your first order',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 50,
    usageLimit: 1000,
    usageCount: 0,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c2',
    code: 'SAVE20',
    description: '$20 off orders over $100',
    discountType: 'fixed',
    discountValue: 20,
    minOrderValue: 100,
    usageCount: 0,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c3',
    code: 'FREESHIP',
    description: 'Free shipping on all orders',
    discountType: 'fixed',
    discountValue: 10,
    usageCount: 0,
    active: true,
    createdAt: new Date().toISOString(),
  },
];
